# Generated by Django 4.2.7 on 2023-11-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='numero_chip',
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paneltrabajador.mascota'),
            preserve_default=False,
        ),
    ]
