# Generated by Django 4.2.7 on 2023-11-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0002_remove_cita_numero_chip_cita_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='mascota',
        ),
    ]
