# Generated by Django 4.2.7 on 2023-11-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0004_cita_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(default="2023-11-23 17:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='paneltrabajador.cliente'),
        ),
    ]
