# Generated by Django 4.2.7 on 2023-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0005_cita_fecha_alter_cita_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='n_cita',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
