# Generated by Django 4.2.7 on 2023-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0007_alter_cliente_rut_alter_factura_numero_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
