# Generated by Django 4.2.7 on 2023-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0009_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numero_chip',
            field=models.BigIntegerField(),
        ),
    ]
