# Generated by Django 4.2.7 on 2023-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0011_alter_mascota_numero_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('0', 'Disponible'), ('1', 'Reservada'), ('2', 'Cancelada')], max_length=1),
        ),
    ]
