# Generated by Django 4.2.7 on 2023-12-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paneltrabajador', '0016_blogentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogEntry',
        ),
    ]
